version: "3"
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: spring_security_demo
    ports:
      - "3307:3306"
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8000:80"
    depends_on:
      - mysql
  app:
    image: openjdk:20-jdk
    stdin_open: true
    container_name: app
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
    depends_on:
      - mysql
