version: '3'
services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: spring_security_demo
    ports:
      - "3307:3306"
  app:
    build: .
    ports:
      - '8000:8080'
    depends_on:
      - db
